# -*- coding: utf-8 -*-
"""
analyze_tier2.py
================
Expert Tier-2 analyses for the modified residue (8OG / PUU / M1A) on
existing trajectories, beyond the basic CVs in analyze_v2.py.

Computes per-frame:
  1. **N7-H7 H-bonds** — the new donor 8oxoG introduces. Donor=N7-H7,
     acceptor scan over protein heavy atoms (N*, O*, S*) and other RNA
     bases. Geometric criterion: D-A < 3.5 A AND D-H...A angle > 120 deg.
  2. **O8 H-bonds** — the new acceptor 8oxoG introduces. Acceptor=O8,
     donor scan over protein N-H, O-H, S-H groups (with explicit H atoms).
  3. **Hoogsteen-edge SASA** — solvent-accessible surface area of the
     N7/O8 face of 8OG. High SASA = exposed; low = buried by stacking
     or protein.
  4. **Backbone dihedrals at modified residue** — alpha (O3'(i-1)-P-O5'-C5'),
     beta (P-O5'-C5'-C4'), gamma (O5'-C5'-C4'-C3'), delta (C5'-C4'-C3'-O3'),
     epsilon (C4'-C3'-O3'-P(i+1)), zeta (C3'-O3'-P(i+1)-O5'(i+1)).
     Compare distribution to canonical RNA "suite" (Richardson 2008).

Outputs per replica:
    tier2_hbonds.csv   per-frame counts: n_N7H7_donor_hb, n_O8_acceptor_hb
    tier2_sasa.csv     per-frame Hoogsteen-edge SASA (A^2)
    tier2_backbone.csv per-frame alpha..zeta (deg)

Aggregate (cross-replica):
    tier2_summary.json    means + reproducibility per system
    figures/tier2_*.png   (optional; generated by separate plotter)

Usage:
    python analyze_tier2.py \\
        --topology .../system/<NAME>.solvated.pdb \\
        --prmtop   .../system/<NAME>.prmtop \\
        --trajectory .../r{N}/traj.dcd \\
        --label 4BS2_8OG_G3 --replica r1 \\
        --mod-resid 177 --mod-resname 8OG \\
        --out /data/.../results/
"""

from __future__ import annotations
import argparse
import json
import sys
import warnings
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore",
    message="DCDReader currently makes independent timesteps")
warnings.filterwarnings("ignore", message="Element information is missing")


# ── Geometry helpers ────────────────────────────────────────────────────────

def dihedral(p0, p1, p2, p3):
    p0 = np.asarray(p0); p1 = np.asarray(p1)
    p2 = np.asarray(p2); p3 = np.asarray(p3)
    b0 = p1 - p0
    b1 = p2 - p1
    b2 = p3 - p2
    b1n = b1 / np.linalg.norm(b1, axis=-1, keepdims=True)
    v = b0 - (b0 * b1n).sum(-1, keepdims=True) * b1n
    w = b2 - (b2 * b1n).sum(-1, keepdims=True) * b1n
    x = (v * w).sum(-1)
    y = (np.cross(b1n, v) * w).sum(-1)
    return np.degrees(np.arctan2(y, x))


def hbond_DH_A_angle(D, H, A):
    """Angle of D-H...A in degrees."""
    HD = D - H
    HA = A - H
    cos = (HD * HA).sum() / (np.linalg.norm(HD) * np.linalg.norm(HA) + 1e-12)
    return np.degrees(np.arccos(np.clip(cos, -1.0, 1.0)))


# ── Main ────────────────────────────────────────────────────────────────────

def run(args):
    import MDAnalysis as mda
    from MDAnalysis import transformations as trans
    from MDAnalysis.analysis import align
    from MDAnalysis.analysis.distances import distance_array

    out_dir = args.out / args.label / args.replica
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n=== Tier-2: {args.label} / {args.replica} ===")
    if args.prmtop and args.prmtop.exists():
        u = mda.Universe(str(args.prmtop), str(args.trajectory),
                         topology_format="PRMTOP", format="DCD")
    else:
        u = mda.Universe(str(args.topology), str(args.trajectory))
    n_frames = len(u.trajectory) // args.stride
    print(f"  Frames: {len(u.trajectory)}  (stride {args.stride} -> {n_frames})")

    # Apply unwrap + center
    prot = u.select_atoms("protein and not name H*")
    rna  = u.select_atoms("not protein and not resname WAT HOH SOL TIP3 "
                          "Na+ Cl- K+ Mg+ Ca+ Zn+ NA CL K MG CA ZN "
                          "and not name H*")
    if hasattr(u.atoms, "bonds") and len(u.atoms.bonds) > 0:
        try:
            u.trajectory.add_transformations(
                trans.unwrap(prot + rna),
                trans.center_in_box(prot, wrap=True),
            )
            print("  PBC unwrap + center ON")
        except Exception as exc:
            print(f"  unwrap failed: {exc}")

    # Modified residue selections
    mod = u.select_atoms(f"resid {args.mod_resid}")
    if not len(mod):
        sys.exit(f"ERROR: no atoms at resid {args.mod_resid}")
    mod_resname = mod.residues[0].resname.strip()
    print(f"  Mod residue: resid={args.mod_resid} resname={mod_resname}")

    # ── Atom selections for H-bond analysis ────────────────────────────────
    # 8OG-specific: N7 (acceptor or donor depending on context) + H7
    # (newly added proton). Only relevant for OGI/8OG residues.
    n7  = mod.select_atoms("name N7")
    h7  = mod.select_atoms("name H7")
    o8  = mod.select_atoms("name O8")
    if not (len(n7) == 1 and len(h7) == 1 and len(o8) == 1):
        print(f"  WARN: 8OG-specific atoms (N7,H7,O8) not all found; "
              f"got n7={len(n7)} h7={len(h7)} o8={len(o8)}")
        n7_atom = n7[0] if len(n7) else None
        h7_atom = h7[0] if len(h7) else None
        o8_atom = o8[0] if len(o8) else None
    else:
        n7_atom = n7[0]; h7_atom = h7[0]; o8_atom = o8[0]

    # Acceptors for N7-H7 donor scan: protein/RNA N* O* S* heavy atoms
    # excluding the 8OG residue itself
    acceptor_pool = u.select_atoms(
        f"(protein or (not resname WAT HOH TIP3 Na+ Cl- K+)) "
        f"and (name N* or name O* or name S*) "
        f"and not (resid {args.mod_resid}) "
        f"and not name H*"
    )
    print(f"  Acceptor pool size: {len(acceptor_pool)}")

    # Donor pool for O8 acceptor scan: heavy atom + bonded H. Build
    # (donor, hydrogen) pairs once.
    donors_heavy = u.select_atoms(
        f"(protein or (not resname WAT HOH TIP3 Na+ Cl- K+)) "
        f"and (name N* or name O* or name S*) "
        f"and not (resid {args.mod_resid})"
    )
    # For each donor-heavy atom, find bonded H atoms (within 1.2 A using
    # one initial frame snapshot). Only keep heavy atoms that have at
    # least one bonded H (i.e. they're H-bond donors).
    u.trajectory[0]
    donor_h_pairs: list[tuple[int, int]] = []
    for h_pool in u.select_atoms("name H*"):
        # find nearest heavy in donors_heavy within 1.2 A
        if not len(donors_heavy):
            continue
        d = np.linalg.norm(donors_heavy.positions - h_pool.position, axis=1)
        i_min = int(d.argmin())
        if d[i_min] < 1.2:
            donor_h_pairs.append((donors_heavy[i_min].index, h_pool.index))
    print(f"  Donor-H pairs (universe-wide, excluding mod residue): "
          f"{len(donor_h_pairs)}")
    donor_idx = np.array([p[0] for p in donor_h_pairs])
    h_idx     = np.array([p[1] for p in donor_h_pairs])

    # ── Backbone dihedral atom lookup at modified residue and neighbors ────
    def get_atom(resid, name):
        sel = u.select_atoms(f"resid {resid} and name {name}")
        return sel[0] if len(sel) else None

    # alpha = O3'(i-1) - P(i) - O5'(i) - C5'(i)
    alpha_atoms = [get_atom(args.mod_resid - 1, "O3'"),
                   get_atom(args.mod_resid,     "P"),
                   get_atom(args.mod_resid,     "O5'"),
                   get_atom(args.mod_resid,     "C5'")]
    beta_atoms  = [get_atom(args.mod_resid, "P"),
                   get_atom(args.mod_resid, "O5'"),
                   get_atom(args.mod_resid, "C5'"),
                   get_atom(args.mod_resid, "C4'")]
    gamma_atoms = [get_atom(args.mod_resid, "O5'"),
                   get_atom(args.mod_resid, "C5'"),
                   get_atom(args.mod_resid, "C4'"),
                   get_atom(args.mod_resid, "C3'")]
    delta_atoms = [get_atom(args.mod_resid, "C5'"),
                   get_atom(args.mod_resid, "C4'"),
                   get_atom(args.mod_resid, "C3'"),
                   get_atom(args.mod_resid, "O3'")]
    epsilon_atoms = [get_atom(args.mod_resid,     "C4'"),
                     get_atom(args.mod_resid,     "C3'"),
                     get_atom(args.mod_resid,     "O3'"),
                     get_atom(args.mod_resid + 1, "P")]
    zeta_atoms    = [get_atom(args.mod_resid,     "C3'"),
                     get_atom(args.mod_resid,     "O3'"),
                     get_atom(args.mod_resid + 1, "P"),
                     get_atom(args.mod_resid + 1, "O5'")]

    BB_NAMES = ["alpha", "beta", "gamma", "delta", "epsilon", "zeta"]
    BB_ATOMS = [alpha_atoms, beta_atoms, gamma_atoms, delta_atoms,
                epsilon_atoms, zeta_atoms]

    # ── Hoogsteen-edge SASA (computed via Shrake-Rupley on Hoogsteen
    # face atoms — N7, C8, O8, H7, C5).
    hoogsteen_face = mod.select_atoms("name N7 or name C8 or name O8 or name H7 or name C5")

    # ── Iterate trajectory ────────────────────────────────────────────────
    times = np.zeros(n_frames)
    n_n7h7_hb = np.zeros(n_frames, dtype=np.int32)
    n_o8_hb   = np.zeros(n_frames, dtype=np.int32)
    sasa_hoogsteen = np.zeros(n_frames)

    bb_dihedrals = np.zeros((n_frames, len(BB_NAMES)))

    print("Iterating frames ...")
    f = 0
    for ts in u.trajectory[::args.stride]:
        # Time
        times[f] = ts.time
        box3 = ts.dimensions[:3].astype(float) if ts.dimensions is not None else None

        # N7-H7 → acceptor H-bonds
        if n7_atom is not None and h7_atom is not None and len(acceptor_pool):
            d_h7_acc = np.linalg.norm(
                acceptor_pool.positions - h7_atom.position, axis=1)
            d_n7_acc = np.linalg.norm(
                acceptor_pool.positions - n7_atom.position, axis=1)
            close = (d_n7_acc < args.hbond_dist) & (d_h7_acc < d_n7_acc)
            count = 0
            for i_acc in np.where(close)[0]:
                ang = hbond_DH_A_angle(n7_atom.position, h7_atom.position,
                                        acceptor_pool[i_acc].position)
                if ang > args.hbond_angle:
                    count += 1
            n_n7h7_hb[f] = count

        # O8 ← donor H-bonds
        if o8_atom is not None and len(donor_idx):
            donor_pos = u.atoms.positions[donor_idx]
            h_pos     = u.atoms.positions[h_idx]
            d_donor_o8 = np.linalg.norm(donor_pos - o8_atom.position, axis=1)
            close = d_donor_o8 < args.hbond_dist
            count = 0
            for i_d in np.where(close)[0]:
                ang = hbond_DH_A_angle(donor_pos[i_d], h_pos[i_d],
                                        o8_atom.position)
                if ang > args.hbond_angle:
                    count += 1
            n_o8_hb[f] = count

        # Hoogsteen face SASA (very rough — Shrake-Rupley would be ideal
        # but is in MDAnalysis.analysis.sasa which is recent. Simpler:
        # count waters within 4 A of any Hoogsteen face atom).
        if len(hoogsteen_face):
            wat_o = u.select_atoms("name O and resname WAT HOH TIP3")
            if len(wat_o):
                d = distance_array(hoogsteen_face.positions, wat_o.positions,
                                   box=ts.dimensions)
                sasa_hoogsteen[f] = float(np.sum(d.min(axis=1) < 4.0))
            else:
                sasa_hoogsteen[f] = np.nan

        # Backbone dihedrals
        for j, atoms in enumerate(BB_ATOMS):
            if all(a is not None for a in atoms):
                bb_dihedrals[f, j] = dihedral(*[a.position for a in atoms])
            else:
                bb_dihedrals[f, j] = np.nan

        if ts.frame % 500 == 0:
            print(f"  frame {ts.frame:5d} t={ts.time/1000:.1f} ns  "
                  f"N7H7-hb={n_n7h7_hb[f]} O8-hb={n_o8_hb[f]} "
                  f"hoog-sasa={sasa_hoogsteen[f]:.0f}")
        f += 1

    times = times[:f]
    n_n7h7_hb = n_n7h7_hb[:f]
    n_o8_hb = n_o8_hb[:f]
    sasa_hoogsteen = sasa_hoogsteen[:f]
    bb_dihedrals = bb_dihedrals[:f]

    # ── Save ──────────────────────────────────────────────────────────────
    np.savetxt(out_dir / "tier2_hbonds.csv",
               np.column_stack([times, n_n7h7_hb, n_o8_hb]),
               delimiter=",",
               header="time_ps,n_N7H7_donor_hb,n_O8_acceptor_hb",
               comments="")
    np.savetxt(out_dir / "tier2_sasa.csv",
               np.column_stack([times, sasa_hoogsteen]),
               delimiter=",",
               header="time_ps,n_water_within_4A_of_Hoogsteen_face",
               comments="")
    np.savetxt(out_dir / "tier2_backbone.csv",
               np.column_stack([times, bb_dihedrals]),
               delimiter=",",
               header="time_ps," + ",".join(BB_NAMES),
               comments="")

    # Summary
    summary = {
        "label": args.label, "replica": args.replica,
        "mod_resid": args.mod_resid, "mod_resname": mod_resname,
        "n_frames": int(f),
        "metrics": {
            "n_N7H7_hb":   {"mean": float(np.mean(n_n7h7_hb)),
                            "max":  int(np.max(n_n7h7_hb)) if f else 0},
            "n_O8_hb":     {"mean": float(np.mean(n_o8_hb)),
                            "max":  int(np.max(n_o8_hb)) if f else 0},
            "hoog_water":  {"mean": float(np.nanmean(sasa_hoogsteen))},
            **{name: {"mean": float(np.nanmean(bb_dihedrals[:, i])),
                      "std":  float(np.nanstd(bb_dihedrals[:, i]))}
               for i, name in enumerate(BB_NAMES)},
        },
    }
    (out_dir / "tier2_summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nWrote {out_dir / 'tier2_*.csv'} and tier2_summary.json")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--topology",   required=True, type=Path)
    ap.add_argument("--prmtop",     required=False, type=Path, default=None)
    ap.add_argument("--trajectory", required=True, type=Path)
    ap.add_argument("--label",      required=True)
    ap.add_argument("--replica",    required=True)
    ap.add_argument("--mod-resid",  type=int, required=True)
    ap.add_argument("--mod-resname", default="8OG")
    ap.add_argument("--out",        type=Path, required=True)
    ap.add_argument("--stride",     type=int, default=1)
    ap.add_argument("--hbond-dist", type=float, default=3.5)
    ap.add_argument("--hbond-angle", type=float, default=120.0)
    args = ap.parse_args()
    run(args)


if __name__ == "__main__":
    main()
