# -*- coding: utf-8 -*-
"""
Generate two sets of MD simulation files for 4BS2:
  1) WT — protein + RNA as-is
  2) 8OG — G3 on chain B mutated to 8-oxoguanosine

Each set is a self-contained directory with:
  - prepared PDB (cleaned, H added)
  - run_openmm.py (ready to execute)
  - 8OG_RNA_amber.xml (for the mutant set only)
  - README.txt
"""

import sys, shutil
from pathlib import Path
from datetime import datetime

# -- paths --
PROJECT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT / "app"))

CIF_PATH   = PROJECT / "4BS2.cif"
OUT_WT     = PROJECT / "output" / "4BS2_WT_MD"
OUT_8OG    = PROJECT / "output" / "4BS2_8OG_G3_MD"
XML_8OG    = PROJECT / "app" / "ff_custom" / "8OG_RNA_amber.xml"

# -- force field files --
FF_PROTEIN = ["amber14/protein.ff14SB.xml"]
FF_RNA     = ["amber14/RNA.OL3.xml"]
FF_WATER   = ["amber14/tip3p.xml"]


def prepare_pdb(cif_path: Path, out_pdb: Path):
    """CIF -> cleaned PDB with hydrogens (PDBFixer)."""
    from pdbfixer import PDBFixer
    from openmm.app import PDBFile

    print(f"  Loading {cif_path.name} ...")
    fixer = PDBFixer(str(cif_path))

    print("  Finding missing residues ...")
    fixer.findMissingResidues()
    # Remove terminal missing residues (disordered tails)
    chains = list(fixer.topology.chains())
    to_del = []
    for cid, reslist in fixer.missingResidues.items():
        chain = chains[cid]
        nres = len(list(chain.residues()))
        # Only keep internal missing residues
        # (skip those at chain termini which are often disordered)
    fixer.findMissingAtoms()
    fixer.addMissingAtoms()
    print("  Adding hydrogens (pH 7.0) ...")
    fixer.addMissingHydrogens(7.0)

    out_pdb.parent.mkdir(parents=True, exist_ok=True)
    with open(out_pdb, "w") as f:
        PDBFile.writeFile(fixer.topology, fixer.positions, f)
    print(f"  -> {out_pdb}")
    return out_pdb


def apply_8og(pdb_path: Path, chain_id: str, resnum: int, out_pdb: Path):
    """Apply 8OG modification to a guanosine residue."""
    from ptm_builder import apply_ptm
    print(f"  Applying 8OG to chain {chain_id} residue G{resnum} ...")
    pdb_str = apply_ptm(pdb_path, chain_id, resnum, "8OG")
    out_pdb.parent.mkdir(parents=True, exist_ok=True)
    out_pdb.write_text(pdb_str, encoding="utf-8")
    print(f"  -> {out_pdb}")
    return out_pdb


def write_openmm_script(pdb_name: str, ff_files: list, water_files: list,
                         extra_xml_names: list, out_dir: Path):
    """Write run_openmm.py to out_dir."""
    ff_list = ", ".join(f"'{f}'" for f in ff_files + water_files + extra_xml_names)
    all_labels = ff_files + water_files + extra_xml_names
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")

    script = f"""\
# -*- coding: utf-8 -*-
# Generated by all_atom MD Setup  {ts}
# Structure : 4BS2 (RRM domain + RNA)
# Force fields : {', '.join(all_labels)}
from pathlib import Path
from openmm import *
from openmm.app import *
from openmm.unit import *

HERE = Path(__file__).parent

# --- Load prepared structure ---
pdb = PDBFile(str(HERE / '{pdb_name}'))
ff  = ForceField({ff_list})

# --- Solvation ---
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addSolvent(ff,
    padding=1.0*nanometer,
    ionicStrength=0.15*molar,
    positiveIon='Na+', negativeIon='Cl-')
print(f"System: {{modeller.topology.getNumAtoms()}} atoms")

# --- Create system (HMR enables 4 fs timestep) ---
system = ff.createSystem(
    modeller.topology,
    nonbondedMethod=PME,
    nonbondedCutoff=1.2*nanometer,
    constraints=HBonds,
    hydrogenMass=1.5*amu,
)

# --- Integrator: Langevin, 300 K, 4 fs ---
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 4*femtoseconds)

# --- Platform: CUDA > OpenCL > CPU ---
for pname in ('CUDA', 'OpenCL', 'CPU'):
    try:
        platform = Platform.getPlatformByName(pname)
        print(f"Using platform: {{pname}}")
        break
    except Exception:
        continue

props = {{'CudaPrecision': 'mixed'}} if pname == 'CUDA' else {{}}
sim = Simulation(modeller.topology, system, integrator, platform, props)
sim.context.setPositions(modeller.positions)

# --- Energy minimization ---
print("Minimizing...")
sim.minimizeEnergy(maxIterations=1000)

# --- NVT equilibration 100 ps ---
print("NVT equilibration (100 ps)...")
sim.context.setVelocitiesToTemperature(300*kelvin)
sim.reporters.append(StateDataReporter('nvt.log', 500,
    step=True, potentialEnergy=True, temperature=True))
sim.step(25000)

# --- NPT equilibration 100 ps ---
print("NPT equilibration (100 ps)...")
system.addForce(MonteCarloBarostat(1*atmosphere, 300*kelvin))
sim.context.reinitialize(preserveState=True)
sim.reporters.append(StateDataReporter('npt.log', 500,
    step=True, potentialEnergy=True, volume=True, temperature=True))
sim.step(25000)

# --- Production 10 ns ---
print("Production MD (10 ns)...")
sim.reporters.append(DCDReporter('traj.dcd', 5000))
sim.reporters.append(StateDataReporter('md.log', 5000,
    step=True, time=True, potentialEnergy=True,
    temperature=True, progress=True, remainingTime=True,
    speed=True, totalSteps=2500000))
sim.step(2500000)
print("Done.")
"""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "run_openmm.py").write_text(script, encoding="utf-8")
    print(f"  -> {out_dir / 'run_openmm.py'}")


def main():
    print("=" * 60)
    print("4BS2 MD Setup: WT + 8OG mutant")
    print("=" * 60)

    # ── Step 1: Prepare WT PDB ────────────────────────────────────────────────
    print("\n[1/4] Preparing WT structure ...")
    wt_pdb = OUT_WT / "4BS2_prepared.pdb"
    prepare_pdb(CIF_PATH, wt_pdb)

    # ── Step 2: Write WT OpenMM script ────────────────────────────────────────
    print("\n[2/4] Writing WT MD files ...")
    write_openmm_script("4BS2_prepared.pdb", FF_PROTEIN + FF_RNA, FF_WATER,
                         [], OUT_WT)
    readme_wt = (
        f"4BS2 Wild-Type MD Setup\n"
        f"=======================\n"
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        f"Structure: 4BS2 — RRM domain (chain A, 174 aa) + RNA (chain B, 12 nt)\n"
        f"FF: AMBER ff14SB (protein) + RNA.OL3 (RNA) + TIP3P\n\n"
        f"To run:\n"
        f"  conda activate allatom\n"
        f"  cd {OUT_WT}\n"
        f"  python run_openmm.py\n\n"
        f"Output: traj.dcd (trajectory), md.log, nvt.log, npt.log\n"
    )
    (OUT_WT / "README.txt").write_text(readme_wt, encoding="utf-8")

    # ── Step 3: Apply 8OG to G3 on chain B ────────────────────────────────────
    print("\n[3/4] Applying 8OG modification (chain B, G3) ...")
    pdb_8og = OUT_8OG / "4BS2_8OG_G3.pdb"
    apply_8og(wt_pdb, "B", 3, pdb_8og)

    # ── Step 4: Write 8OG OpenMM script ───────────────────────────────────────
    print("\n[4/4] Writing 8OG MD files ...")
    shutil.copy(XML_8OG, OUT_8OG / "8OG_RNA_amber.xml")
    write_openmm_script("4BS2_8OG_G3.pdb", FF_PROTEIN + FF_RNA, FF_WATER,
                         ["8OG_RNA_amber.xml"], OUT_8OG)
    readme_8og = (
        f"4BS2 8-Oxoguanosine (G3->8OG) MD Setup\n"
        f"=======================================\n"
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        f"Structure: 4BS2 — RRM domain (chain A) + RNA (chain B)\n"
        f"Modification: G3 (chain B) -> 8-oxoguanosine (8OG)\n"
        f"FF: AMBER ff14SB (protein) + RNA.OL3 + 8OG_RNA_amber.xml + TIP3P\n\n"
        f"To run:\n"
        f"  conda activate allatom\n"
        f"  cd {OUT_8OG}\n"
        f"  python run_openmm.py\n\n"
        f"Output: traj.dcd (trajectory), md.log, nvt.log, npt.log\n"
    )
    (OUT_8OG / "README.txt").write_text(readme_8og, encoding="utf-8")

    print("\n" + "=" * 60)
    print("DONE! Two directories generated:")
    print(f"  WT  : {OUT_WT}")
    print(f"  8OG : {OUT_8OG}")
    print("=" * 60)


if __name__ == "__main__":
    main()
